#!/usr/bin/env tsx
/**
 * setup-wallets.ts
 * One-command testnet wallet setup for Metered.
 *
 * Usage:
 *   npx tsx scripts/setup-wallets.ts
 *
 * What it does:
 *   1. Generates 2 Stellar keypairs (server + agent)
 *   2. Funds both via Friendbot (XLM)
 *   3. Establishes USDC trustline on both accounts
 *   4. Writes keys to .env
 *   5. Prints instructions for funding USDC
 */

import { Keypair, Horizon, TransactionBuilder, Networks, Operation, Asset } from '@stellar/stellar-sdk'
import { existsSync, writeFileSync, readFileSync } from 'fs'
import { createInterface } from 'readline'

const HORIZON_URL = 'https://horizon-testnet.stellar.org'
const FRIENDBOT_URL = 'https://friendbot.stellar.org'
const USDC_ISSUER = 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5' // testnet
const USDC = new Asset('USDC', USDC_ISSUER)
const horizon = new Horizon.Server(HORIZON_URL)

// ── Helpers ───────────────────────────────────────────────────────────────────
async function friendbot(publicKey: string): Promise<void> {
  const res = await fetch(`${FRIENDBOT_URL}?addr=${publicKey}`)
  if (!res.ok) throw new Error(`Friendbot failed for ${publicKey}: ${res.status}`)
}

async function addUsdcTrustline(keypair: Keypair): Promise<void> {
  const account = await horizon.loadAccount(keypair.publicKey())
  const tx = new TransactionBuilder(account, {
    fee: '100',
    networkPassphrase: Networks.TESTNET,
  })
    .addOperation(Operation.changeTrust({ asset: USDC }))
    .setTimeout(30)
    .build()
  tx.sign(keypair)
  await horizon.submitTransaction(tx)
}

async function confirm(question: string): Promise<boolean> {
  const rl = createInterface({ input: process.stdin, output: process.stdout })
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close()
      resolve(answer.toLowerCase().startsWith('y'))
    })
  })
}

function writeEnv(serverKp: Keypair, agentKp: Keypair, existingEnv: string): void {
  // Preserve any user-set vars (BRAVE_API_KEY, etc.) if .env already exists
  const lines = existingEnv ? existingEnv.split('\n') : []
  const preserved = lines
    .filter((l) => l.startsWith('BRAVE_API_KEY=') || l.startsWith('SERVER_URL=') || l.startsWith('PORT='))
    .join('\n')

  const content = [
    '# Generated by scripts/setup-wallets.ts — Stellar testnet',
    `STELLAR_NETWORK=testnet`,
    '',
    '# Server wallet — receives payments',
    `MPP_SECRET_KEY=${serverKp.secret()}`,
    `STELLAR_RECIPIENT=${serverKp.publicKey()}`,
    '',
    '# Agent wallet — pays for services',
    `AGENT_SECRET_KEY=${agentKp.secret()}`,
    `AGENT_BUDGET=0.10`,
    '',
    '# Optional',
    preserved || 'BRAVE_API_KEY=',
    'SERVER_URL=http://localhost:3000',
  ]
    .join('\n')
    .trimEnd()

  writeFileSync('.env', content + '\n')
}

// ── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log('\n🪐 Metered — Testnet Wallet Setup\n' + '─'.repeat(40))

  // Check if .env already exists
  let existingEnv = ''
  if (existsSync('.env')) {
    const ok = await confirm('.env already exists. Overwrite? (y/N) ')
    if (!ok) {
      console.log('Aborted.')
      process.exit(0)
    }
    existingEnv = readFileSync('.env', 'utf8')
  }

  // 1. Generate keypairs
  console.log('\n1️⃣  Generating keypairs...')
  const serverKp = Keypair.random()
  const agentKp = Keypair.random()
  console.log(`   Server: ${serverKp.publicKey()}`)
  console.log(`   Agent:  ${agentKp.publicKey()}`)

  // 2. Fund via Friendbot
  console.log('\n2️⃣  Funding with XLM via Friendbot...')
  await Promise.all([friendbot(serverKp.publicKey()), friendbot(agentKp.publicKey())])
  console.log('   ✅ Both accounts funded with 10,000 XLM (testnet)')

  // 3. USDC trustlines
  console.log('\n3️⃣  Adding USDC trustlines...')
  await addUsdcTrustline(serverKp)
  await addUsdcTrustline(agentKp)
  console.log('   ✅ USDC trustline established on both accounts')

  // 4. Write .env
  console.log('\n4️⃣  Writing .env...')
  writeEnv(serverKp, agentKp, existingEnv)
  console.log('   ✅ .env written')

  // 5. USDC funding instructions
  console.log(`
5️⃣  Fund with testnet USDC (required to pay for services):

   Option A — Stellar testnet USDC faucet:
   https://horizon-testnet.stellar.org/friendbot?addr=${agentKp.publicKey()}

   Option B — Use Stellar Lab to send USDC from another testnet account.

   Option C — Run on mainnet with real USDC in your agent wallet.

─────────────────────────────────────────
✅ Setup complete. Next steps:

   npm run server          # start the API server
   npm run agent           # run the demo agent (default budget: 0.10 USDC)
   npm run agent "question" 0.05   # custom question + budget
─────────────────────────────────────────
`)
}

main().catch((err) => {
  console.error('❌', err.message)
  process.exit(1)
})
